### ISSUE TITLE
Working with latest version of linux?

### ISSUE THREAD

**Issue by eric-ibarra** [twteamware/raspberrypi-ptp#1] opened 2018-10-22 12:40 UTC
This guide looks very comprehensive, however, I'm unable to get this to work with the latest version at https://github.com/raspberrypi/linux

It appears that the patches are not needed since the tweaks appear to already be implemented in the mainline. Ethtool does not display tx timestamping though. Do you have any recommendations on getting this to work?

Alternatively, do you know the commit hash of the version that you used?

**Comment by gizero** [comment] 2018-11-07 13:20
Hi! I haven't had a chance to test it with kernel `>4.9`. As you suggest [this patch](https://github.com/twteamware/raspberrypi-ptp/blob/master/patches/0001-smsc95xx-use-generic-ethtool_op_get_ts_info-callback.patch) has already been upstreamed in current https://github.com/raspberrypi/linux and shouldn't be necessary anymore.

Can you provide the output you are getting from `ethtool`? Moreover, can you check `CONFIG_NETWORK_PHY_TIMESTAMPING` is enabled in your `.config`?

https://github.com/raspberrypi/linux/commit/a2f34d45809d8685bca1e91989e35746499ac400 is the latest commit I used and tested.

**Comment by gizero** [comment] 2018-11-28 14:40
@eric-ibarra FYI: I updated instructions by targeting currently latest Raspbian. I'm closing this one since I can't reproduce the problem you described with current sources. Feel free to comment/reopen if you still have issues.

**Closed as completed by gizero** 2018-11-28 14:40 UTC
